# Using full WAS Libery image
FROM s390x/websphere-liberty:full

# Image by default operates by non-root user, so in order to do configuration we need to use root
USER root

# Creating JENKINS_HOME folder. Can be ignored/replaced by mounted storage for persistence
RUN mkdir -p /opt/jenkins && chmod g+rwx /opt/jenkins

# Updating repo's
RUN apt-get update

# wget required to download jenkins from web
RUN apt-get install -y wget

# Downloading jenkins generic java package. Other versions here - https://www.jenkins.io/download/
RUN wget -P /config/dropins/ http://mirrors.jenkins.io/war-stable/2.235.4/jenkins.war

# Changing permissions to allow access for non-root users within the group
RUN chmod g+rwx /config/dropins/jenkins.war

# Copying jvm.options from this repo.
COPY --chown=1001:0 jvm.options /config/

# Switching back to non-root user
USER 1001
