# Using kernel WAS Libery image
FROM s390x/websphere-liberty:kernel

# Image by default operates by non-root user, so in order to do configuration we need to use root
USER root

# Creating JENKINS_HOME folder. Can be ignored/replaced by mounted storage for persistence
RUN mkdir -p /opt/jenkins && chmod g+rwx /opt/jenkins

# Updating repo's
RUN apt-get update

# Installing addons - wget requires for download from web, xz-utils are required for unpacking tar.xz archives, git is self-explenatory
RUN apt-get install -y wget xz-utils git

# Downloading jenkins generic java package. Other versions here - https://www.jenkins.io/download/. If no further configuration will be needed, you can use /config/dropins folder instead
RUN wget -P /config/apps/ http://mirrors.jenkins.io/war-stable/2.235.4/jenkins.war

# Changing permissions to allow access for non-root users within the group
RUN chmod g+rwx /config/apps/jenkins.war

# Copying jvm.options and server.xml from this repo.
COPY --chown=1001:0 jvm.options /config/
COPY --chown=1001:0 server.xml /config/

# Verbose argument will show you the output of configure.sh script
ARG VERBOSE=true

# Avoiding server double start & stop as part of creation of a SCC layer. Requires a lot of resources in case of true value
ARG OPENJ9_SCC=false

# Configuring server based on provided server.xml
RUN configure.sh

# Installing NodeJS
ARG NODE_VERSION=12.18.3
RUN wget https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-s390x.tar.xz
RUN tar -xf node-v${NODE_VERSION}-linux-s390x.tar.xz
RUN mv node-v${NODE_VERSION}-linux-s390x /usr/local/lib/nodejs
RUN chmod g+rwx /usr/local/lib/nodejs

# Adding NodeJS to PATH
ENV NODE_PATH /usr/local/lib/nodejs/lib/node_modules
ENV PATH /usr/local/lib/nodejs/bin:$PATH

# Exposing port (you can use any) for worker nodes
EXPOSE 45420

# Switching back to non-root user
USER 1001
